npm:
  filename: "tmp/npm.json"
  api:
    yesterday: "https://registry.npmjs.org/-/all/static/yesterday.json"
    today: "https://registry.npmjs.org/-/all/static/today.json"
    all: "https://registry.npmjs.org/-/all"
