# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  # To prevent commiting your credentials or personal token, use a `.env` file
  # instead (see: https://github.com/bkeepers/dotenv)
  exceptions_slack_webhook_url: <%= ENV["EXCEPTIONS_SLACK_WEBHOOK_URL"] %>
  jobs_slack_webhook_url: <%= ENV["JOBS_SLACK_WEBHOOK_URL"] %>

  # You can use your GitHub credentials but we recommend you generate a Personal Access
  # Token  (https://github.com/settings/tokens) instead. Under "Select scopes", simply
  # check "public_repo". You can then use that token as the value for the `username` key
  # and leave `password` empty.
  github_username: <%= ENV["GITHUB_USERNAME"] %>
  github_password: <%= ENV["GITHUB_PASSWORD"] %>

  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>

development:
  <<: *default
  secret_key_base: 65110d8b1e70d744bea8abe2b0200998648c1b5f5cb6aeeb1f6b784ee66c087d297580ac702290f8fcf80b96468787e32130ab4a24fec3451bc9e2188e0e98ef

test:
  <<: *default
  secret_key_base: 0e4bbdc7bade440de3e6cf27d3a4ae40be4f5cb46f590532593419dedc0f230354ccd576fbf96477a2622617c632a229aa1fe06b50508eb3e191ba9275346fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
